---
title: "Syllabus"
---
## Course Overview

This course is a rigorous analysis of the real numbers, as well as an introduction to writing and communicating mathematics well.

We will:

- Learn the content and techniques of analysis, so that you can creatively solve problems you have never seen before.
- Learn to read and write rigorous proofs, so that you can convincingly defend your reasoning in the language of mathematics.
- Learn good mathematical writing skills and style, so that you can communicate your ideas effectively.

Topics will include: construction of the real numbers, fields, complex numbers, topology of the reals, metric spaces, careful treatment of sequences and series, functions of real numbers, continuity, compactness, connectedness, differentiation, and the mean value theorem, with an introduction to sequences of functions.

## Lectures and Office Hours

**Lectures**: Mondays and Wednesdays in Shan 2421.

- Section 1: 1:15--2:30 PM
- Section 2: 2:45--4:00 PM

**Office Hours**: TBD

## Textbook and Online Tools

The textbook is *Principles of Mathematical Analysis* by Walter Rudin.

[A note: it is OK if you find the writing in the Rudin book to be challenging and/or terse. This is a great opportunity to engage with a different mathematical writing style than what you may have encountered in other texts so far. I encourage you to use the course notes and the textbook together to see how these different styles can complement each other.]{.aside}

We will be using a variety of online tools to supplement the lecture material for this course:

- Our main course hub is here on this site. You will find links to access all lecture videos, lecture notes, and other course materials here. Lecture videos will also be posted on Youtube. You can also find links for Gradescope on our Canvas page.
- I will post coursework here under the Assignments link and on Gradescope, and we will use Gradescope to submit coursework.
- I will send announcements via email, and I am available to message via email any time.

## Logistics and policies

### Guiding Principles for the Course

I suggest a few principles to guide us this semester:

**Prioritize physical and mental health**

- You're always welcome to talk to me about things you're going through.
- You never owe me any personal information about your health or anything else.
- If I can't help you, I usually know someone who can.
- Some good resources: [Student Health Services](https://services.claremont.edu/student-health-services/), [Monsour Counseling](https://services.claremont.edu/mcaps/), [Wellness Resources](https://www.hmc.edu/health-wellness/resources/), [Claremont Colleges Care Guide](https://www.hmc.edu/student-life/wp-content/uploads/sites/4/2013/05/The-Claremont-Colleges-Care-Guide.pdf).

**The humane option is the best option**

- We are going to focus on supporting each other as humans.
- We are going to seek simple solutions when challenges arise.
- We are going to share resources and communicate clearly.

**We will remain flexible**

- Everybody needs support and empathy.
- Some expectations may need to change.
- Schedules may need to be adjusted.
- If you need any help or accommodation, just ask. I'll work with you.

### The Honor Code

The HMC Honor Code applies in all matters of conduct concerning this course. It is forbidden to use course solutions or materials provided by previous students, found online, or through any third party source. The struggle and joy of discovering a solution is an important part of this course. Homework sets are meant to help you practice and learn. If you resort to using solutions you find, as opposed to challenging yourself to develop your own solutions, you are doing yourself a disservice (and you won’t do as well on exams).

### External resources for homeworks: what's OK, what's not OK

The teaching team is well aware of the plethora of tools and solutions that are available to you, both online or within our student community. We want to be clear about what is OK and not OK with regards to these resources.

**What's OK**

- I encourage you first and foremost to talk to the Prof, the grutors, and/or each other!
- Cooperation on all homework assignments is encouraged. It is appropriate to acknowledge the assistance of others; if you work with others on a homework question, please cite them as collaborators on your Overleaf submission. You should understand your solutions well enough to write them up yourself.
- Feel free to consult sources beyond your textbook and class notes when formulating your homework solutions.

It is crucial that you cite any and every external source you access (including other textbooks, any online resources, solution keys, collaborators, etc.)

**What’s Not OK**

- Using complete versions solutions found online, including accessing these solutions via sites such as Chegg. Please note that I know there are easy to find solutions online to almost all of the problems in our textbook.
- Using solutions from previous or current students as your own work. Copying is prohibited, and you should understand your solutions well enough to write them up yourself.
- Using solutions from ChatGPT or other generative language models as your own work. This is equivalent to copying as in the previous two bullet points.
- Uploading your solutions to sites such as Chegg or providing your solutions for others to copy.

These will be regarded as a violation of the HMC Honor Code and will be handled accordingly. 

---
## Grading and Assessment
The coursework that you do in Math 131 contributes to your overall course grade, which we will use to ultimately assign you a letter grade. Your overall course grade will be calculated as follows:

- 5% attendance
- 20% homework assignments 
- 5% project
- 20% midterm exam 1
- 20% midterm exam 2
- 20% final exam
- The highest exam score of midterm 1, midterm 2, or final will contribute an additional 10%.

Grades will be assigned on a straight scale based on your overall percentage as calculated above. I commit to honor the following minimum cutoffs:

- 94% or higher guarantees an A,
- 84% or higher guarantees (at least) a B,
- 74% or higher guarantees (at least) a C,
- 64% or higher guarantees (at least) a D.

Remember that your grade in this course (and any other course, for that matter) is only a measurement of your learning at one moment in time. It is never a measure of your potential ability or your worth!

### Attendance

You will be expected to attend the in-class lectures regularly and to complete the assigned reading/videos before coming to lecture. To account for illness, travel, and other contingencies, you may miss up to 3 lecture days without penalty, no questions asked. You do not need to email the professor when using these "days off." 

If you require to miss class for more than three days for extenuating circumstances (e.g., prolonged illness or family emergency), you should contact the DSA staff and I will work in consultation with DSA to make a plan for your situation. 

### Homework
Homework assignments serve several important purposes, including to further familiarize you with the course material, practice mathematical techniques, provide challenges in creative problem solving, and improve your mathematical writing skills and style. 

Homework will be assigned most weeks. Assignments will be submitted directly to Gradescope. [Using Gradescope: If you are registered for this course, you should have already been added to the Gradescope class page. Contact your instructor if you are having problems with access. Gradescope has several tutorial resources, e.g. Gradescope video tutorials.  See the document Gradescope Instructions for Students for an overview of how to submit your homework sets.]{.aside} 

LaTeX is an important part of written mathematical communication, and one aim of this course is for students to gain comfort and confidence in LaTeX. To this end, homework assignments must be typed in LaTeX. A LaTeX template will be provided for each homework assignment.

Due dates and LaTeX template links can be found under the "Assignments" page on this site. 

### Homework Grading Policies

Your overall homework grade will be the mean of all of your homework scores. 

Late submission policy: Each student is granted three late assignments over the semester, no questions asked. Late submissions should be submitted within 72 hours.  When submitting work late, you must upload it electronically to Gradescope, which will automatically track the late hours. You do not need to email the professor when using these grace hours. 

If you require extensions for extenuating circumstances (e.g., prolonged illness or family emergency), you should contact the DSA staff and I will work in consultation with DSA to make a plan for your situation. 

### Exams
Exams are an opportunity for you to review and synthesize your learning, demonstrate your proficiency with the material, and assess your progress. Further information about exams is forthcoming.

- **Midterm 1**: Monday October 9
- **Midterm 2**: Monday November 13
- **Final**: TBA

### Project

Further information about the project is forthcoming.

## Equity, Diversity, and Inclusion

Mathematics has been practiced and developed by all cultures throughout human history. Despite this, the mathematics community has not always been welcoming and inclusive. Unfortunately, our community still struggles with issues of equity, diversity, and inclusion. I am committed to fostering and promoting equity and justice for all voices within mathematics. This collective work begins (but does not end) in the classroom.

It is important that each of you has a safe, respectful, and open environment to grow in your mathematical identity. I welcome your feedback on ways to make our community of learners in Math 131 more inclusive.

### Diversity
I enthusiastically embrace diversity of gender, sexual orientation, race, ethnicity, national origin, family status, socioeconomic background, and other visible and non-visible categories. I do not tolerate discrimination.

### Names/Pronouns
You deserve to be addressed in the manner you prefer. To guarantee that I address you properly, you are welcome to tell me your preferred name and/or pronouns at any time, either in conversation or via email.

### Title IX
You deserve a learning community that is free from discrimination, sexual harassment, a hostile environment, sexual assault, domestic violence, and stalking. If you experience or witness a Title IX violation, you have many options for support and/or reporting. See the [Title IX Resources Chart](https://www.hmc.edu/student-life/wp-content/uploads/sites/4/2020/02/Resource-Flow-Chart-2020-Final.pdf).

As faculty members, we are obligated to report any disclosures related to the HMC community that involve Title IX violations.

### Accessibility
My goal is to make our course accessible to all of you! To request academic accommodations, visit the [Office of Accessible Education website](https://www.hmc.edu/student-life/disability-resources/). 

Please send us any questions; I am happy to help.