---
title: "Lecture 4: Fields, Order, and Bounds"
date: 09/11/2023
date-format: "ddd DD MMMM YYYY"
published-title: Lecture Date
author: Heather Zinn Brooks
description: "So far we've met some interesting infinite sets, including the natural numbers, the rationals, and the reals. In this lecture, we'll explore some structural and algebraic properties that these sets have. How are they similar, and how are they different? What is it that makes the real numbers so special?"
---

::: {.hidden}
\newcommand{\R}{\mathbb{R}}
\newcommand{\Q}{\mathbb{Q}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\C}{\mathbb{C}}
:::

## Lecture Videos

{{< video https://www.youtube.com/embed/iAJLebUUztw >}}
{{< video https://www.youtube.com/embed/h3UxjI8mr3g >}}

## Order

If we want an intuitive notion of order on our set, it turns out we need it to satisfy just a few properties, which we define below.

::: {.callout-note icon=false appearance="minimal"}
::: {#def-order}
## Order
An **order** on a set $S$ is a relation $<$ satisfying two properties.

1. *Trichotomy*. If $x, y \in S,$ exactly one of the following statements is true: $x < y, \ x = y, \text{ or } y < x.$
[We can define $x > y$ as equivalent to $y < x$. We can also define $x \leq y$ as equivalent to $x<y$ or $x=y$.]{.aside}
2. *Transitivity*. If $x, y, z \in S$, and if $x < y$ and $y<z,$ then $x < z.$
:::
:::

You'll notice that this is pretty flexible, and it actually allows us to define order in many different ways.

**Example.** In $\Z,$ we say $m<n$ if $n-m$ is positive, that is, if $n-m$ is in the set $\{1, 2, 3, \dots \}$.

**Example.** In $\Z \times \Z$ we could define a *dictionary* or *lexicographic* order: We say $(a,b) < (c,d)$ if $a<c$ or if $a=c$ and $b<d.$

::: {.callout-important icon=false appearance="minimal"}
## In-class activity
Prove that the two examples above are orders on their respective sets.
:::

## Fields and Ordered Fields

Some sets have special properties.

A **field** is a set with two operations $+$ and $\times.$ A field must be closed under both operations and satisfy axioms for commutativity, associativity, identity, and inverses for both operations. It must additionally obey the distributive law with respect to the given operations. A complete list of the field axioms as defined in Rudin is reproduced below.

Our set $F$ is a field if it satisfies the following axioms:

**Axioms for addition**

- If $x, y \in F$, then $x+y \in F$ (*closure*)
- $x+y = y+x$ for all $x, y \in F.$ (*commutativity*)
- $(x+y) + z = x + (y+z)$ for all $x,y, z \in F.$ (*associativity*)
- $F$ contains an element $0$ such that $0 + x = x$ for every $x \in F$. (*identity*)
- To every $x\in F$ corresponds an element $-x \in F$ such that $x + (-x) = 0$. (*inverse*)

**Axioms for multiplication**

- If $x, y \in F$, then $xy \in F$. (*closure*)
- $xy = yx$ for all $x, y \in F.$ (*commutativity*)
- $(xy)z = x(yz)$ for all $x,y, z \in F.$ (*associativity*)
- $F$ contains an element $1$ such that $1x = x$ for every $x \in F$. (*identity*)
- If $x\in F$ and $x \neq 0$ then there exists an element $1/x \in F$ such that $x\left(1/x\right)=1$. (*inverse*)

**The distributive law**

- $x(y+z)=xy+xz$ holds for all $x, y, z \in F.$

In this class, we will work with a few fields that you have already encountered in previous courses: $\Q, \R,$ and $\C.$ Notice that $\N$ and $\Z$ are not fields: can you see why?

You'll find more exploration of special algebraic structures of sets in an abstract algebra course.[At HMC, this is Math 171.]{.aside} 

If we have a set that is ordered and a field, and the field operations "play nicely" with the order, then we have a set that's called an **ordered field**. Let's define that more precisely now.

::: {.callout-note icon=false appearance="minimal"}
::: {#def-orderedfield}
## Ordered field
Suppose $F$ is a field and $F$ has an order. We say that $F$ is an ordered field that satisfies the following two additional properties. 

1. If $x,y,z \in F$, then $y<z$ implies that $y+x < z+x$.
2. Furthermore, if $y<z$ and $x>0$, then $xy < xz.$
:::
:::


**Example.** $\Q$ and $\R$ are both ordered fields. 

::: {.callout-warning icon=false}
An ordered field is not just a set that is ordered and a field. For example, the complex field $\C$ can have an order, but is *not* an ordered field: you'll show this in homework.

A set has to satisfy the additional properties about the operations provided in the definition to be an ordered field.
:::

If we have an ordered field, this means we can apply our field operations and have order be affected in the way that we have come to intuitively expect from our experience with the reals. If we add the same number to two different numbers, the bigger one stays bigger. If we multiply two numbers by a positive number, the bigger one stays bigger.


## Least Upper Bounds and Greatest Lower Bounds

Once we have a notion of ordering, we become empowered to look for biggest and smallest elements (and whether or not sets even have a biggest or smallest element). 

::: {.callout-note icon=false appearance="minimal"}
::: {#def-upperbound}
## Upper bound and lower bound
Let $E \subset S$ be an ordered set. If there is an element $\beta \in S$ such that for all $x \in E$ we have $x\leq \beta$, then $\beta$ is an **upper bound** for $E$. If $E$ has an upper bound we say that $E$ is **bounded above**. [Notice that $\beta$ does not need to be in the set to be an upper bound for the set.]{.aside}

Similarly, we can define a **lower bound** and **bounded below.**
:::
:::

::: {.callout-important icon=false appearance="minimal"}
## In-class activity
In class, we will find an upper bound for a given set and prove that it is an upper bound.
:::

Notice that it might be possible to define many upper bounds for a set. It's natural to ask whether you could find a smallest one. If a smallest upper bound exists, we'll call it the **least upper bound** or **supremum** of the set.

::: {.callout-note icon=false appearance="minimal"}
::: {#def-supinf}
## Least upper bound/supremum
We again consider $E \subset S.$ If there exists an $\alpha \in S$ such that

1. $\alpha$ is an upper bound of $E$, and
2. if $\gamma < \alpha$, then $\gamma$ is not an upper bound of $E$,

then we say $\alpha$ is the **least upper bound** or **supremum** of $E$. We write $\alpha = \sup E.$
:::
:::

Analogously, we can define the **greatest lower bound** or **infimum** of $E$, which we denote $\inf E.$

::: {.callout-important icon=false appearance="minimal"}
## In-class activity
In class, we will explore a variety of sets to determine what their suprema are (if they exist).
:::

::: {.callout-warning icon=false}
Supremum and maximum are not the same thing. An element $\alpha$ is the **maximum** of a set $E$ if $x \leq \alpha$ for all $x \in E$ and *it is an element of* $E$. 
:::

That is, if the maximum exists, it is the supremum, but a set can have a supremum but no maximum.

**Example.** Consider the sets $\{x \in \R: x < 0\}$ and $\{x \in \R: x \leq 0\}.$ Zero is the supremum of both sets, but only the second set has zero as a maximum because zero is included in the set.

**Properties of suprema:**

[Here, I will use the shorthand ($\implies$) for "implies" and ($\iff$) for "if and only if" (a bidirectional implication).]{.aside}

- $\gamma$ is an upper bound for $A \iff \sup A \leq \gamma.$
- For all $a \in A, a \leq \gamma \iff \sup A \leq \gamma.$
- For all $a \in A, a < \gamma \implies \sup A \leq \gamma.$ (Careful! Notice the inequality here is not strict)
- If $\gamma < \sup A,$ then there exists $a \in A$ such that $\gamma < a \leq \sup A.$

::: {.callout-note icon=false appearance="minimal"}
::: {#thm-supremaorder}
If $A \subset B$, and $\sup A$ and $\sup B$ exist, then $\sup A \leq \sup B.$
:::

::: {.proof}
Because $A \subset B$, we know that for all $a \in A,$ $a$ is also in $B.$ It follows that $a \leq \sup B.$ Thus, by the second property above, $\sup A \leq \sup B.$
:::
:::

To show that two sets have the same supremum, we can use a similar strategy as we would use to show that two sets are the same: we show that $\sup A \leq \sup B$, and similarly that $\sup B \leq \sup A.$

## Completeness of $\R$

As we'll show in class, not every set that has an upper bound has a supremum. 

::: {.callout-note icon=false appearance="minimal"}
::: {#def-name}
## Axiom of Completeness
A set $S$ satisfies the **Axiom of Completeness** or the **least upper bound property** if every nonempty subset of $S$ that has an upper bound has a supremum in $S$. [We include *nonempty* because if $E = \emptyset$ then everything is vacuously an upper bound.]{.aside}
:::
:::

In this lecture, we've encountered some important differences between the infinite sets $\N, \Q, \R,$ and $\C.$ The natural numbers aren't a field, meaning they're missing some important algebraic structure. All of these sets can be given an order, but the complex numbers aren't an ordered field.

What is the distinction between the rationals and the reals? Intuitively, we might think about the rationals as having "gaps" that are "filled in" by the reals: we know that $x^2=2$ does not have a solution in $\Q$, but it does in $\R.$ This is because $\R$ satisfies the axiom of completeness.

::: {.callout-note icon=false appearance="minimal"}
::: {#thm-reals}
## Completeness of the Reals
There exists an ordered field $\R$ which satisfies the completeness axiom that contains $\Q$ as a subfield.
:::
:::

We will save a more rigorous construction of $\R$ for later in the course, but for now we will appreciate some amazing consequences of this theorem, which we explore further in class.

- We can write any real number as a decimal expansion, for example
$$
\sqrt{2} = \sup \{1, 1.4, 1.41, 1.414, 1.4142, ...\}
$$
- In the reals, roots exist: We can define
$$
a^{1/n} \triangleq \sup \{r \in Q: r^n < a\},
$$
provided that $a>0$ if the set is even (so that the set is nonempty).
[$\triangleq$ means "is defined to be"]{.aside}

There are two more nice consequences which we will define and prove in class.

::: {.callout-important icon=false appearance="minimal"}
## In-class activity
In class, we will prove the **Archimedean Property** of $\R$, and then use it to show that $\Q$ is dense in $\R.$ 
:::
